    language : php

    php:
      - 5.5
      - 5.6
      - 7.0
      - 7.1
      - 7.2
      - hhvm
    # Commands to be run before your environment runs.
    before_script:
      - composer self-update
      - composer install --prefer-source --no-interaction --dev
    # Commands you want to run that will verify your build.
    script: phpunit
    # allow_failures: Allow this build to fail under the specified environments.
    # fast_finish: If your build fails do not continue trying to build, just stop.
    matrix:
      allow_failures:
        - php: 5.6
        - php: hhvm
      fast_finish: true
    # Customize when the notification emails are sent.
    services:
      - mysql

    before-install:
      - composer self-update
    # Install composer dependencies,
    # Create database, schema and fixtures
    install:
      - composer install
    
    # After a build, send email notification with the build results
    notifications:
      email: temetangcindy@gmail.com