language: php

php:
  - 8.0.1

services:
  - mysql

before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXIST customers;' -U root

script:
 # - php index.php
  - echo "app is ready to deploy"

deploy:
  provider: script
  script: bash ./deploy.sh